### ISSUE TITLE
Frequency Agility over 5 Channels

### ISSUE THREAD

**Issue by Pyrrvs** [TI-LPRF-Software/RemoTI-Linux#3]
Hi,

I have a question more than an issue so I will close this issue as resolved once answered.

Is it somehow possible to force the CC2531 to do frequency agility over more than the 3 standard channels (15, 20, 25) without having to rewrite the RF4CE network layer ?

I would like to be able to specify which channels should be used for frequency agility.

Thank you,
Gauthier

**Comment by joseTI** [comment]
Hi Pyrrvs,

I am afraid that doing something like what you describe would involve modifying the network layer.

Regards,
joseTI

**Comment by Pyrrvs** [comment]
Thank you for your quick reply.

I'll dig into the network layer code then.

Regards,
Gauthier
